services:

  app:
    container_name: lms-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    environment:
      - DOTNET_ENVIRONMENT=DevContainers
    volumes:
      - .:/workspace
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      - development

  database:
    container_name: lms-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DevelopmentDB"
      MSSQL_SA_PASSWORD: "N&DevelopmentPassword"
    networks:
      - development

networks:
  development:
    driver: bridge
